apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
    - name: websecure
      port: 443
      protocol: TCP
  selector:
    app: traefik
---
